/** Representative queries and the card that must rank first. Run on every content or ranking change. */
export const searchExpectations: { query: string; expectedFirst: string }[] = [
  { query: "max heap", expectedFirst: "heap-max-negation" },
  { query: "maxheap", expectedFirst: "heap-max-negation" },
  { query: "max-heap", expectedFirst: "heap-max-negation" },
  { query: "largest first heap", expectedFirst: "heap-max-negation" },
  { query: "priority queue", expectedFirst: "heap-min" },
  { query: "pop left", expectedFirst: "deque-queue" },
  { query: "queue pop left", expectedFirst: "deque-queue" },
  { query: "queue", expectedFirst: "deque-queue" },
  { query: "sort returns none", expectedFirst: "sort-vs-sorted" },
  { query: "sort second descending", expectedFirst: "sort-multi-key" },
  { query: "sort by two fields", expectedFirst: "sort-multi-key" },
  { query: "first >= target", expectedFirst: "bisect-left" },
  { query: "first greater equal", expectedFirst: "bisect-left" },
  { query: "lower bound", expectedFirst: "bisect-left" },
  { query: "upper bound", expectedFirst: "bisect-right" },
  { query: "class factory", expectedFirst: "classmethod" },
  { query: "classmethod", expectedFirst: "classmethod" },
  { query: "static vs class", expectedFirst: "classmethod" },
  { query: "mutable dataclass field", expectedFirst: "dataclass-default-factory" },
  { query: "list default class", expectedFirst: "dataclass-default-factory" },
  { query: "dataclass list default", expectedFirst: "dataclass-default-factory" },
  { query: "whole regex", expectedFirst: "regex-fullmatch" },
  { query: "match whole string", expectedFirst: "regex-fullmatch" },
  { query: "regex full match", expectedFirst: "regex-fullmatch" },
  { query: "dict default list", expectedFirst: "defaultdict" },
  { query: "copy nested list", expectedFirst: "shallow-deep-copy" },
  { query: "filter iterator", expectedFirst: "filter-map-iterators" },
  { query: "default mutable argument", expectedFirst: "mutable-default-argument" },
  { query: "graph bfs", expectedFirst: "bfs-template" },
  { query: "__init__", expectedFirst: "class-init" },
  { query: "constructor", expectedFirst: "class-init" },
  { query: "custom comparator", expectedFirst: "cmp-to-key" },
  { query: "defualtdict", expectedFirst: "defaultdict" },
  { query: "dijkstra", expectedFirst: "dijkstra" },
];
